### ISSUE TITLE
Change Keyboard option to Done to Next

### ISSUE THREAD

**Issue by sohijain** [tylersuehr7/chips-input-layout#11]
HI,

I am using this for chips but i want enter on keyboard when chip created. Now it is showing done and when i click on it keyboard hide. So please help me to find the solution.

Thank You

**Comment by tylersuehr7** [comment]
Hi sohijain,

I'm not understanding the issue too well, but I think you mean the IME option on the keyboard being the action done option. Currently, when you are allowing custom chips to be entered by the user, being action done is the intended functionality so that it can create the chip with the inputted text. 

I can probably change this in the future though for when you are not allowing the user to enter custom chips.
