### ISSUE TITLE
Does something like "onTextChanged"?

### ISSUE THREAD

**Issue by knkmsht** [tylersuehr7/chips-input-layout#12]
I want to implement the chiplist update with the keyboard input.

Is there an example?

**Comment by tylersuehr7** [comment]
Hi knkmsht,

The ChipsInputLayout will allow you to set a chip list that is filterable by inputting text from the keyboard input. You can use this feature by aggregating your chips in a List data structure and then setting it in the ChipsInputLayout using the method, setFilterableChipList(List).

For more specific details, check this out: https://github.com/tylersuehr7/chips-input-layout#setting-a-filterable-list-of-chips-in-chipsinputlayout

**Comment by juandavidGF** [comment]
But isn't it possible to get set an `OnTextChanged` listener in order to (let's say) fetch a new list of `Chip`s and change the current filterable list?

Have in mind that although the primary use case for this is the _fetch mobile contacts_ example, but there are a lot of cases like _fetch a contacts list from an API_, an API that you might not want to fetch it entirely in the case you have something like 20,000 contacts, maybe?
