### ISSUE TITLE
ChipSelectionObserver  method name inconsistent 

### ISSUE THREAD

**Issue by erikswed** [tylersuehr7/chips-input-layout#15]
Thanks for the chips-input-layout i l really like it.
Maybe the `ChipSelectionObserver ` method name `onChipDeselected` should be called 
"onChipDeleted" since that is what happens..

```
public interface ChipSelectionObserver {
    void onChipSelected(Chip addedChip);

    void onChipDeselected(Chip removedChip);
}
```

**Comment by tylersuehr7** [comment]
Thanks, I'm happy to hear that you like the library!!

Thanks for the feedback too! Currently, when onChipDeselected(...) is called it's not fully deleting the chip, it's just moving the chip from the selected list back to the filtered list. 

Also this observer may change in the future, I'm trying to create a new observer that will also return the correct position of the chip so that the adapter can use animations instead of just refreshing the entire list.

**Comment by erikswed** [comment]
aha I see, but how do I delete a custom chip like
`chipsInputLayout.addSelectedChip(new CountryChip(filters.getCountry()));`

When I press the chip "x" button it is removed from the layout but you say its moved. What´s the dif from selected list and filtered list. Maybe I should set setChipsDeletable(true) and then it´s not moved?

**Comment by tylersuehr7** [comment]
Yeah, that's the main reason I want to add a new observer for internal components only lol

Long story short, originally you couldn't add custom chips (so you could only have chips in either selected or filtered) and that's when I had created the selection observer with those method names. After I added custom chips, they still used the onChipDeselected(...) method but could not be placed into the filtered list because they didn't originate from it, so they were just removed from the selected list only.

**Comment by erikswed** [comment]
Nice it´s a work in progress I understand. Thanks keep it up

**Comment by tylersuehr7** [comment]
Sure thing, thanks!
