### ISSUE TITLE
Readonly chips

### ISSUE THREAD

**Issue by majid701** [tylersuehr7/chips-input-layout#27]
Is it possible to use the library to show a set of chips which are not deletable by the user?
The readme is unclear on this functionality. If its supported how can it be implemented?

thanks, great library tho 😄

**Comment by tylersuehr7** [comment]
Hi majid701,


Thanks for your question! 

It's not possible to display a fully 'read-only' set of chips using this library because it's modeled after the chips in the Material Design Guide - which only specifies editable chips such as contacts and stuff - so that functionality doesn't exist. 

In this library, you can achieve similar to a 'read-only' chip list by preventing the user from clicking on chips and hiding the delete button. However, the user can still use the software keyboard to delete chips though. You can do this by declaring so in the XML view: 
app:chip_showDelete="false"
app:chip_showDetails="false"

Currently, I don't have any plans for making chips 'read-only' for this library but you're more than welcomed to fork this project and implement such a feature using the design patterns and components from this one!


Thanks,
Tyler
